name: Publish ISOs

on:
  schedule:
    - cron: '42 2 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ${{ github.repository_owner }}
  # renovate: datasource=github-releases depName=kairos-io/AuroraBoot
  AURORABOOT_VERSION: 0.2.7

jobs:
  build:
    strategy:
      matrix:
        variant:
        - ubuntu-intel-nuc
        #- ubuntu-nvidia

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.4.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}/kairos-${{ matrix.variant }}

      - name: Build iso from the container image
        id: build-iso
        uses: docker://quay.io/kairos/auroraboot:v0.2.7
        with:
          args: >-
            --set "state_dir=/github/workspace"
            --debug
            ${{ matrix.variant }}/auroraboot.yaml

      - name: Rename ISO
        run: |-
          mv ./build/kairos.iso.custom.iso \
            kairos-${{ matrix.variant }}-${{ steps.meta.outputs.version }}.iso

      - name: Publish ISO
        uses: softprops/action-gh-release@v1
        id: publish-iso
        if: ${{ github.event_name != 'pull_request' }}
        with:
          files: kairos-${{ matrix.variant }}-${{ steps.meta.outputs.version }}.iso
